apiRules:
- include:
    uidRegex: ^DocFxForUnity
    type: Namespace
- include:
    uidRegex: ^Global
    type: Namespace
- include:
    uidRegex: ^Game.HotUpdate.Web.Data
    type: Namespace
- include:
    uidRegex: ^Game.HotUpdate.Web
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace